baseURL = "https://sondr3.github.io/nix-expressions/"
languageCode = "en-us"
title = "Nix Channels - Sondre Nilsen"
theme = "book"

disablePathToLower = true

[markup.tableOfContents]
  startLevel = 1

[param]
  BookToC = true
  BookSection = "*"
  BookRepo = "https://github.com/sondr3/nix-expressions"
  BookSearch = false
  BookComments = false
